spring:
  data:
    mongodb:
#      username: matasoy
#      password: password
      host: localhost
      port: 27017
      database: readingisgood

jwt:
  secret: bWF0YXNveWRlcmtpa2l0YXBva3VtYWtvbmVtbGlhbWFhaWxlaGVwc2luZGVuZGFoYW9uZW1saQ==bWF0YXNveWRlcmtpa2l0YXBva3VtYWtvbmVtbGlhbWFhaWxlaGVwc2luZGVuZGFoYW9uZW1saQ==


